### ISSUE TITLE
Upload b32decode hotfix to PyPI

### ISSUE THREAD

**Issue by xrat** [WhyNotHugo/totp-cli#12]
I installed totp-cli 1.2.0 via `pip install totp` and hit the `NameError: name 'b32decode' is not defined`. I know it's easily fixed but coming from https://pypi.org/project/totp/ there is no (at least no trivial) path to this repository here because the Homepage link is broken.

I'd be great if the fix for b32decode could be pushed to PyPI and if the Homepage link of the PyPI site/package could be fixed.

**Comment by MountainX** [comment]
What is the fix for `NameError: name 'b32decode' is not defined`?

**Comment by WhyNotHugo** [comment]
I've not idea what this bug is, and I've never come across it. Can you provide some reproduction steps?

Current version on PyPI is the latest from `master`.

**Comment by xrat** [comment]
Commit https://github.com/WhyNotHugo/totp-cli/commit/7383ddd35e3a23408872b3f16f292084050fcb49 is dated 2019-02-03. The latest version on PyPI according to https://pypi.org/project/totp/#history is 1.2.0 dated 2019-01-30.

**Comment by WhyNotHugo** [comment]
Ah, you're right, I was looking at the wrong branch. Just pushed a new tag, should show up on PyPI in a while.

**Comment by xrat** [comment]
It's up already. And thanks for fixing the homepage link too.

**Comment by WhyNotHugo** [comment]
You're welcome! Thanks for pointing it out.

--
Hugo Osvaldo Barrera
