### ISSUE TITLE
Function b32decode not defined

### ISSUE THREAD

**Issue by Jzarecta** [WhyNotHugo/totp-cli#15]
I am trying to get totp to work with a website, and when I add the key it gives me the following error: 
```
  File "/usr/lib/python3.8/site-packages/totp/cli.py", line 84, in input_shared_key
    b32decode(shared_key.upper())
NameError: name 'b32decode' is not defined
```

Regards.

**Comment by WhyNotHugo** [comment]
What version are you using? This was fixed quite some time ago by #11

**Comment by Jzarecta** [comment]
I am on totp 1.3.0 installed it from pip

Seems there is an issue on the project side where there is totp and totp-cli (1.0) however the totp-cli hasnt been marked obsolete and installing both it overwrites the totp (1.3)

**Comment by WhyNotHugo** [comment]
`totp-cli` is the name of the project, but `totp` is the cli command you use to interact with it.

I don't quite follow how you have both versions installed. What's the output of `cat $(which totp)`?
(I wish I'd added a `--version` command :facepalm: )

**Comment by Jzarecta** [comment]
do a pip search and will find both totp and totp-cli one on 1.0 and the other with 1.3.0
https://pypi.org/project/totp-cli/
and
https://pypi.org/project/totp/

**Comment by WhyNotHugo** [comment]
Check the homepage on both packages, they're different project (albeit, the naming of the former is quite unfortunate and confusing, to say the least).
