### ISSUE TITLE
Please release new AUR package

### ISSUE THREAD

**Issue by halcyon** [WhyNotHugo/totp-cli#2]
Please release a new AUR package, thanks!

**Comment by WhyNotHugo** [comment]
The AUR package contains the latest code. There are no unreleased commits either.

**Comment by halcyon** [comment]
According to https://aur.archlinux.org/cgit/aur.git/log/?h=totp-cli the last change was made 12 days ago. Yet the latest commit to totp-cli was merged 9 days ago. Specifically pr #1  is not included in 0.1.1 the most recent and only release of https://pypi.python.org/pypi/totp - I downloaded it and examined it.

**Comment by WhyNotHugo** [comment]
Sorry, my bad. Looks like my local copy was out-of-date. 😅
Pushed a new tag and updated the AUR package.

**Comment by WhyNotHugo** [comment]
Minor nitpick: looks like the public key for the keypair used to sign your commit (`BED560C2DEF315F6`) is not available on common public GPG server.
